# Generated by Django 4.0.6 on 2022-07-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa1',
            fields=[
                ('fecha', models.DateField()),
                ('garzon', models.CharField(max_length=20)),
                ('subtotal', models.IntegerField()),
                ('propina', models.IntegerField()),
                ('total', models.IntegerField()),
                ('pago', models.CharField(max_length=20)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa2',
            fields=[
                ('fecha', models.DateField()),
                ('garzon', models.CharField(max_length=20)),
                ('subtotal', models.IntegerField()),
                ('propina', models.IntegerField()),
                ('total', models.IntegerField()),
                ('pago', models.CharField(max_length=20)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
