# Generated by Django 4.0.6 on 2022-07-28 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa1',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mesa1',
            name='propina',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mesa1',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
